services:
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: ubceadev
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ubcea_memberships
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
