// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUsersAdmin = `-- name: CountUsersAdmin :one
WITH args AS (
    SELECT
        $1::text AS full_name,
        $2::text AS student_id,
        $3::text AS email,
        $4::role_type AS role,
        $5::group_type AS "group"
)
SELECT COUNT(*)
FROM users u
CROSS JOIN args a
WHERE (a.full_name IS NULL OR u.full_name ILIKE '%' || a.full_name || '%')
  AND (a.student_id IS NULL OR u.student_id ILIKE '%' || a.student_id || '%')
  AND (a.email IS NULL OR u.email ILIKE '%' || a.email || '%')
  AND (a.role IS NULL OR u.role = a.role)
  AND (
      a."group" IS NULL
      OR EXISTS (
          SELECT 1 FROM user_groups filter_group
          WHERE filter_group.user_id = u.id
            AND filter_group."group" = a."group"
      )
  )
`

type CountUsersAdminParams struct {
	FullName  pgtype.Text
	StudentID pgtype.Text
	Email     pgtype.Text
	Role      NullRoleType
	Group     NullGroupType
}

func (q *Queries) CountUsersAdmin(ctx context.Context, arg CountUsersAdminParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUsersAdmin,
		arg.FullName,
		arg.StudentID,
		arg.Email,
		arg.Role,
		arg.Group,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getUsersAdmin = `-- name: GetUsersAdmin :many
WITH args AS (
    SELECT
        $1::text AS full_name,
        $2::text AS student_id,
        $3::text AS email,
        $4::role_type AS role,
        $5::group_type AS "group",
        $6::integer AS "limit",
        $7::integer AS "offset"
)
SELECT
    u.id,
    u.email,
    u.student_id,
    u.role,
    u.created_at,
    u.updated_at,
    u.full_name,
    u.email_verified_at,
    u.onboarding_completed_at,
    u.avatar_url,
    COALESCE(g.groups, '{}'::text[])::text[] AS groups
FROM users u
CROSS JOIN args a
LEFT JOIN LATERAL (
    SELECT array_agg(ug."group"::text ORDER BY ug.assigned_at, ug."group") AS groups
    FROM user_groups ug
    WHERE ug.user_id = u.id
) g ON true
WHERE (a.full_name IS NULL OR u.full_name ILIKE '%' || a.full_name || '%')
  AND (a.student_id IS NULL OR u.student_id ILIKE '%' || a.student_id || '%')
  AND (a.email IS NULL OR u.email ILIKE '%' || a.email || '%')
  AND (a.role IS NULL OR u.role = a.role)
  AND (
      a."group" IS NULL
      OR EXISTS (
          SELECT 1 FROM user_groups filter_group
          WHERE filter_group.user_id = u.id
            AND filter_group."group" = a."group"
      )
  )
ORDER BY u.created_at DESC
LIMIT (SELECT "limit" FROM args)
OFFSET (SELECT "offset" FROM args)
`

type GetUsersAdminParams struct {
	FullName  pgtype.Text
	StudentID pgtype.Text
	Email     pgtype.Text
	Role      NullRoleType
	Group     NullGroupType
	Limit     pgtype.Int4
	Offset    pgtype.Int4
}

type GetUsersAdminRow struct {
	ID                    pgtype.UUID
	Email                 string
	StudentID             pgtype.Text
	Role                  RoleType
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
	FullName              string
	EmailVerifiedAt       pgtype.Timestamptz
	OnboardingCompletedAt pgtype.Timestamptz
	AvatarUrl             pgtype.Text
	Groups                []string
}

func (q *Queries) GetUsersAdmin(ctx context.Context, arg GetUsersAdminParams) ([]GetUsersAdminRow, error) {
	rows, err := q.db.Query(ctx, getUsersAdmin,
		arg.FullName,
		arg.StudentID,
		arg.Email,
		arg.Role,
		arg.Group,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUsersAdminRow
	for rows.Next() {
		var i GetUsersAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.StudentID,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FullName,
			&i.EmailVerifiedAt,
			&i.OnboardingCompletedAt,
			&i.AvatarUrl,
			&i.Groups,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
