// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUsersAdmin = `-- name: GetUsersAdmin :many
SELECT
    u.id,
    u.email,
    u.student_id,
    u.role,
    u.created_at,
    u.updated_at,
    u.full_name,
    u.email_verified_at,
    u.is_student,
    u.onboarding_completed_at,
    u.avatar_url,
    COALESCE(g.groups, '{}'::text[])::text[] AS groups
FROM users u
LEFT JOIN LATERAL (
    SELECT array_agg(
        ug."group"::text
        ORDER BY ug.assigned_at, ug."group"
    ) AS groups
    FROM user_groups ug
    WHERE ug.user_id = u.id
) g ON true
WHERE (
    $1::text IS NULL
    OR u.full_name ILIKE '%' || $1::text || '%'
)
AND (
    $2::text IS NULL
    OR u.student_id ILIKE '%' || $2::text || '%'
)
AND (
    $3::text IS NULL
    OR u.email ILIKE '%' || $3::text || '%'
)
AND (
    $4::role_type IS NULL
    OR u.role = $4::role_type
)
AND (
    $5::boolean IS NULL
    OR u.is_student = $5::boolean
)
AND (
    $6::group_type IS NULL
    OR EXISTS (
        SELECT 1
        FROM user_groups filter_group
        WHERE filter_group.user_id = u.id
          AND filter_group."group" = $6::group_type
    )
)
ORDER BY u.created_at DESC
LIMIT $8
OFFSET $7
`

type GetUsersAdminParams struct {
	FullName  pgtype.Text
	StudentID pgtype.Text
	Email     pgtype.Text
	Role      NullRoleType
	IsStudent pgtype.Bool
	Group     NullGroupType
	Offset    pgtype.Int4
	Limit     pgtype.Int4
}

type GetUsersAdminRow struct {
	ID                    pgtype.UUID
	Email                 string
	StudentID             pgtype.Text
	Role                  RoleType
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
	FullName              string
	EmailVerifiedAt       pgtype.Timestamptz
	IsStudent             bool
	OnboardingCompletedAt pgtype.Timestamptz
	AvatarUrl             pgtype.Text
	Groups                []string
}

func (q *Queries) GetUsersAdmin(ctx context.Context, arg GetUsersAdminParams) ([]GetUsersAdminRow, error) {
	rows, err := q.db.Query(ctx, getUsersAdmin,
		arg.FullName,
		arg.StudentID,
		arg.Email,
		arg.Role,
		arg.IsStudent,
		arg.Group,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUsersAdminRow
	for rows.Next() {
		var i GetUsersAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.StudentID,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FullName,
			&i.EmailVerifiedAt,
			&i.IsStudent,
			&i.OnboardingCompletedAt,
			&i.AvatarUrl,
			&i.Groups,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
