// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: membership.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCurrentMembershipWithTransaction = `-- name: GetCurrentMembershipWithTransaction :one
SELECT
    m.id,
    m.tier_id,
    m.started_at,
    m.expires_at,
    m.cancelled_at,
    t.id AS transaction_id,
    t.amount_paid_cents,
    t.status,
    t.group_at_purchase
FROM memberships m
JOIN transactions t
    ON t.membership_id = m.id
WHERE m.user_id = $1
    AND m.cancelled_at IS NULL
    AND m.started_at <= NOW()
    AND m.expires_at > NOW()
ORDER BY m.started_at DESC
LIMIT 1
`

type GetCurrentMembershipWithTransactionRow struct {
	ID              pgtype.UUID
	TierID          pgtype.UUID
	StartedAt       pgtype.Timestamptz
	ExpiresAt       pgtype.Timestamptz
	CancelledAt     pgtype.Timestamptz
	TransactionID   pgtype.UUID
	AmountPaidCents pgtype.Int8
	Status          TransactionStatusType
	GroupAtPurchase NullGroupType
}

func (q *Queries) GetCurrentMembershipWithTransaction(ctx context.Context, userID pgtype.UUID) (GetCurrentMembershipWithTransactionRow, error) {
	row := q.db.QueryRow(ctx, getCurrentMembershipWithTransaction, userID)
	var i GetCurrentMembershipWithTransactionRow
	err := row.Scan(
		&i.ID,
		&i.TierID,
		&i.StartedAt,
		&i.ExpiresAt,
		&i.CancelledAt,
		&i.TransactionID,
		&i.AmountPaidCents,
		&i.Status,
		&i.GroupAtPurchase,
	)
	return i, err
}

const getEligibleTiersWithPrices = `-- name: GetEligibleTiersWithPrices :many
SELECT
    mt.id,
    mt.title,
    mt.description,
    mt.stripe_product_id,
    mt.slug,
    mtp.stripe_price_id
FROM membership_tiers mt
JOIN membership_tier_prices mtp
    ON mtp.tier_id = mt.id
JOIN users u
    on u.id = $1
WHERE mt.is_active = TRUE
    AND (
        mt."group" = 'member'
        OR EXISTS (
            SELECT 1
            FROM user_groups ug
            WHERE ug.user_id = u.id AND ug."group" = mt."group"
        )
    )
    AND (
        mtp.is_student_required IS NULL
        OR mtp.is_student_required = u.is_student
    )
`

type GetEligibleTiersWithPricesRow struct {
	ID              pgtype.UUID
	Title           string
	Description     pgtype.Text
	StripeProductID pgtype.Text
	Slug            pgtype.Text
	StripePriceID   pgtype.Text
}

func (q *Queries) GetEligibleTiersWithPrices(ctx context.Context, id pgtype.UUID) ([]GetEligibleTiersWithPricesRow, error) {
	rows, err := q.db.Query(ctx, getEligibleTiersWithPrices, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEligibleTiersWithPricesRow
	for rows.Next() {
		var i GetEligibleTiersWithPricesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.StripeProductID,
			&i.Slug,
			&i.StripePriceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPublicTiersAndPrices = `-- name: GetPublicTiersAndPrices :many
SELECT
    mt.id,
    mt.title,
    mt.description,
    mt.slug,
    mt.stripe_product_id,
    mtp.stripe_price_id,
    mtp.is_student_required
FROM membership_tiers mt
JOIN membership_tier_prices mtp
    ON mtp.tier_id = mt.id
WHERE mt.is_active = TRUE AND mt."group" = 'member'
`

type GetPublicTiersAndPricesRow struct {
	ID                pgtype.UUID
	Title             string
	Description       pgtype.Text
	Slug              pgtype.Text
	StripeProductID   pgtype.Text
	StripePriceID     pgtype.Text
	IsStudentRequired pgtype.Bool
}

func (q *Queries) GetPublicTiersAndPrices(ctx context.Context) ([]GetPublicTiersAndPricesRow, error) {
	rows, err := q.db.Query(ctx, getPublicTiersAndPrices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPublicTiersAndPricesRow
	for rows.Next() {
		var i GetPublicTiersAndPricesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Slug,
			&i.StripeProductID,
			&i.StripePriceID,
			&i.IsStudentRequired,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTierByTierId = `-- name: GetTierByTierId :one
SELECT
    mt.id,
    mt.title,
    mt.description,
    mt.slug,
    mt.stripe_product_id,
    mtp.stripe_price_id,
    mtp.is_student_required
FROM membership_tiers mt
JOIN membership_tier_prices mtp
    ON mtp.tier_id = mt.id
WHERE mt.id = $1
`

type GetTierByTierIdRow struct {
	ID                pgtype.UUID
	Title             string
	Description       pgtype.Text
	Slug              pgtype.Text
	StripeProductID   pgtype.Text
	StripePriceID     pgtype.Text
	IsStudentRequired pgtype.Bool
}

func (q *Queries) GetTierByTierId(ctx context.Context, id pgtype.UUID) (GetTierByTierIdRow, error) {
	row := q.db.QueryRow(ctx, getTierByTierId, id)
	var i GetTierByTierIdRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Slug,
		&i.StripeProductID,
		&i.StripePriceID,
		&i.IsStudentRequired,
	)
	return i, err
}
