// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: membership.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPendingTransaction = `-- name: CreatePendingTransaction :one
INSERT INTO transactions (
    user_id,
    group_at_purchase,
    student_at_purchase,
    purchase_type,
    status
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    'pending'
)
RETURNING id
`

type CreatePendingTransactionParams struct {
	UserID            pgtype.UUID
	GroupAtPurchase   NullGroupType
	StudentAtPurchase pgtype.Bool
	PurchaseType      NullPurchaseType
}

func (q *Queries) CreatePendingTransaction(ctx context.Context, arg CreatePendingTransactionParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createPendingTransaction,
		arg.UserID,
		arg.GroupAtPurchase,
		arg.StudentAtPurchase,
		arg.PurchaseType,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const expirePendingTransactionById = `-- name: ExpirePendingTransactionById :exec
UPDATE transactions
SET
    status = 'expired',
    updated_at = NOW()
WHERE id = $1 AND status = 'pending'
`

func (q *Queries) ExpirePendingTransactionById(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, expirePendingTransactionById, id)
	return err
}

const getAllMembershipsWithTransactions = `-- name: GetAllMembershipsWithTransactions :many
SELECT
    m.id,
    m.tier_id,
    m.started_at,
    m.expires_at,
    m.cancelled_at,
    t.id AS transaction_id,
    t.amount_paid_cents,
    t.status,
    t.group_at_purchase
FROM memberships m
JOIN transactions t
    ON t.membership_id = m.id
WHERE m.user_id = $1
ORDER BY m.started_at DESC
`

type GetAllMembershipsWithTransactionsRow struct {
	ID              pgtype.UUID
	TierID          pgtype.UUID
	StartedAt       pgtype.Timestamptz
	ExpiresAt       pgtype.Timestamptz
	CancelledAt     pgtype.Timestamptz
	TransactionID   pgtype.UUID
	AmountPaidCents pgtype.Int8
	Status          TransactionStatusType
	GroupAtPurchase NullGroupType
}

func (q *Queries) GetAllMembershipsWithTransactions(ctx context.Context, userID pgtype.UUID) ([]GetAllMembershipsWithTransactionsRow, error) {
	rows, err := q.db.Query(ctx, getAllMembershipsWithTransactions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllMembershipsWithTransactionsRow
	for rows.Next() {
		var i GetAllMembershipsWithTransactionsRow
		if err := rows.Scan(
			&i.ID,
			&i.TierID,
			&i.StartedAt,
			&i.ExpiresAt,
			&i.CancelledAt,
			&i.TransactionID,
			&i.AmountPaidCents,
			&i.Status,
			&i.GroupAtPurchase,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCurrentMembershipWithTransaction = `-- name: GetCurrentMembershipWithTransaction :one
SELECT
    m.id,
    m.tier_id,
    m.started_at,
    m.expires_at,
    m.cancelled_at,
    t.id AS transaction_id,
    t.amount_paid_cents,
    t.status,
    t.group_at_purchase
FROM memberships m
JOIN transactions t
    ON t.membership_id = m.id
WHERE m.user_id = $1
    AND m.cancelled_at IS NULL
    AND m.started_at <= NOW()
    AND m.expires_at > NOW()
ORDER BY m.started_at DESC
LIMIT 1
`

type GetCurrentMembershipWithTransactionRow struct {
	ID              pgtype.UUID
	TierID          pgtype.UUID
	StartedAt       pgtype.Timestamptz
	ExpiresAt       pgtype.Timestamptz
	CancelledAt     pgtype.Timestamptz
	TransactionID   pgtype.UUID
	AmountPaidCents pgtype.Int8
	Status          TransactionStatusType
	GroupAtPurchase NullGroupType
}

func (q *Queries) GetCurrentMembershipWithTransaction(ctx context.Context, userID pgtype.UUID) (GetCurrentMembershipWithTransactionRow, error) {
	row := q.db.QueryRow(ctx, getCurrentMembershipWithTransaction, userID)
	var i GetCurrentMembershipWithTransactionRow
	err := row.Scan(
		&i.ID,
		&i.TierID,
		&i.StartedAt,
		&i.ExpiresAt,
		&i.CancelledAt,
		&i.TransactionID,
		&i.AmountPaidCents,
		&i.Status,
		&i.GroupAtPurchase,
	)
	return i, err
}

const getEligibleTiersWithPrices = `-- name: GetEligibleTiersWithPrices :many
SELECT
    mt.id,
    mt.title,
    mt.description,
    mt.stripe_product_id,
    mt.slug,
    mtp.stripe_price_id
FROM membership_tiers mt
JOIN membership_tier_prices mtp
    ON mtp.tier_id = mt.id
JOIN users u
    on u.id = $1
WHERE mt.is_active = TRUE
    AND (
        mt."group" = 'member'
        OR EXISTS (
            SELECT 1
            FROM user_groups ug
            WHERE ug.user_id = u.id AND ug."group" = mt."group"
        )
    )
    AND (
        mtp.is_student_required IS NULL
        OR mtp.is_student_required = u.is_student
    )
`

type GetEligibleTiersWithPricesRow struct {
	ID              pgtype.UUID
	Title           string
	Description     pgtype.Text
	StripeProductID pgtype.Text
	Slug            pgtype.Text
	StripePriceID   pgtype.Text
}

func (q *Queries) GetEligibleTiersWithPrices(ctx context.Context, id pgtype.UUID) ([]GetEligibleTiersWithPricesRow, error) {
	rows, err := q.db.Query(ctx, getEligibleTiersWithPrices, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEligibleTiersWithPricesRow
	for rows.Next() {
		var i GetEligibleTiersWithPricesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.StripeProductID,
			&i.Slug,
			&i.StripePriceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingTransactionForUpdate = `-- name: GetPendingTransactionForUpdate :one
SELECT
    id,
    stripe_checkout_session_id
FROM transactions
WHERE user_id = $1 AND status = 'pending'
FOR UPDATE
`

type GetPendingTransactionForUpdateRow struct {
	ID                      pgtype.UUID
	StripeCheckoutSessionID pgtype.Text
}

func (q *Queries) GetPendingTransactionForUpdate(ctx context.Context, userID pgtype.UUID) (GetPendingTransactionForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getPendingTransactionForUpdate, userID)
	var i GetPendingTransactionForUpdateRow
	err := row.Scan(&i.ID, &i.StripeCheckoutSessionID)
	return i, err
}

const getPublicTiersAndPrices = `-- name: GetPublicTiersAndPrices :many
SELECT
    mt.id,
    mt.title,
    mt.description,
    mt.slug,
    mt.stripe_product_id,
    mtp.stripe_price_id,
    mtp.is_student_required
FROM membership_tiers mt
JOIN membership_tier_prices mtp
    ON mtp.tier_id = mt.id
WHERE mt.is_active = TRUE AND mt."group" = 'member'
`

type GetPublicTiersAndPricesRow struct {
	ID                pgtype.UUID
	Title             string
	Description       pgtype.Text
	Slug              pgtype.Text
	StripeProductID   pgtype.Text
	StripePriceID     pgtype.Text
	IsStudentRequired pgtype.Bool
}

func (q *Queries) GetPublicTiersAndPrices(ctx context.Context) ([]GetPublicTiersAndPricesRow, error) {
	rows, err := q.db.Query(ctx, getPublicTiersAndPrices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPublicTiersAndPricesRow
	for rows.Next() {
		var i GetPublicTiersAndPricesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Slug,
			&i.StripeProductID,
			&i.StripePriceID,
			&i.IsStudentRequired,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTierByTierId = `-- name: GetTierByTierId :one
SELECT
    mt.id,
    mt.title,
    mt.description,
    mt.slug,
    mt.stripe_product_id,
    mtp.stripe_price_id,
    mtp.is_student_required
FROM membership_tiers mt
JOIN membership_tier_prices mtp
    ON mtp.tier_id = mt.id
WHERE mt.id = $1
`

type GetTierByTierIdRow struct {
	ID                pgtype.UUID
	Title             string
	Description       pgtype.Text
	Slug              pgtype.Text
	StripeProductID   pgtype.Text
	StripePriceID     pgtype.Text
	IsStudentRequired pgtype.Bool
}

func (q *Queries) GetTierByTierId(ctx context.Context, id pgtype.UUID) (GetTierByTierIdRow, error) {
	row := q.db.QueryRow(ctx, getTierByTierId, id)
	var i GetTierByTierIdRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Slug,
		&i.StripeProductID,
		&i.StripePriceID,
		&i.IsStudentRequired,
	)
	return i, err
}

const putStripeCheckoutSessionId = `-- name: PutStripeCheckoutSessionId :exec
UPDATE transactions
SET
    stripe_checkout_session_id = $2,
    updated_at = NOW()
WHERE id = $1
`

type PutStripeCheckoutSessionIdParams struct {
	ID                      pgtype.UUID
	StripeCheckoutSessionID pgtype.Text
}

func (q *Queries) PutStripeCheckoutSessionId(ctx context.Context, arg PutStripeCheckoutSessionIdParams) error {
	_, err := q.db.Exec(ctx, putStripeCheckoutSessionId, arg.ID, arg.StripeCheckoutSessionID)
	return err
}

const updateTransactionStatusById = `-- name: UpdateTransactionStatusById :exec
UPDATE transactions
SET
    status = $2,
    updated_at = NOW()
WHERE id = $1
`

type UpdateTransactionStatusByIdParams struct {
	ID     pgtype.UUID
	Status TransactionStatusType
}

func (q *Queries) UpdateTransactionStatusById(ctx context.Context, arg UpdateTransactionStatusByIdParams) error {
	_, err := q.db.Exec(ctx, updateTransactionStatusById, arg.ID, arg.Status)
	return err
}
