// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: profile.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getProfileByUserID = `-- name: GetProfileByUserID :one
SELECT
    u.id,
    u.email,
    u.student_id,
    u.role,
    u.created_at,
    u.updated_at,
    u.full_name,
    u.email_verified_at,
    u.onboarding_completed_at,
    u.avatar_url,
    COALESCE(g.groups, '{}'::text[])::text[] AS groups
FROM users u
LEFT JOIN LATERAL (
    SELECT array_agg(ug."group"::text ORDER BY ug.assigned_at ASC, ug."group" ASC) AS groups
    FROM user_groups ug
    WHERE ug.user_id = u.id
) g ON true
WHERE u.id = $1
`

type GetProfileByUserIDRow struct {
	ID                    pgtype.UUID
	Email                 string
	StudentID             pgtype.Text
	Role                  RoleType
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
	FullName              string
	EmailVerifiedAt       pgtype.Timestamptz
	OnboardingCompletedAt pgtype.Timestamptz
	AvatarUrl             pgtype.Text
	Groups                []string
}

func (q *Queries) GetProfileByUserID(ctx context.Context, id pgtype.UUID) (GetProfileByUserIDRow, error) {
	row := q.db.QueryRow(ctx, getProfileByUserID, id)
	var i GetProfileByUserIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.StudentID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FullName,
		&i.EmailVerifiedAt,
		&i.OnboardingCompletedAt,
		&i.AvatarUrl,
		&i.Groups,
	)
	return i, err
}
